### ISSUE TITLE
Ecrire le rapport Technique

### ISSUE THREAD

**Issue by LueMar-R** [ChainYo/chatbot_brief_simplon#21]
"Un rapport technique sur le projet qui décrit les données, les choix techniques, le modèle utilisé, le code, l’architecture mise en place. Vous devez aussi proposer une solution de déploiement, son coût, et ses avantages. Enfin vous terminerez par une conclusion (performances, recommandations…)."

**Comment by chainyo** [comment]
Relecture à apporter.
Elargir la conclusion.
