### ISSUE TITLE
[5] Générer une banque de questions 

### ISSUE THREAD

**Issue by chainyo** [ChainYo/chatbot_brief_simplon#5]
**Il faut générer une banque de phrase de type questions/interrogations qui seront utilisées par le modèle.**

Ces phrases/questions seront utilisées comme référence par notre modèle pour pouvoir ensuite proposer une réponse.
- [x] Faire une liste des questions potentielles
- [x] Regrouper les questions sur le même sujet ensemble

(lié à #6)

**Comment by sialorama** [comment]
La banque des questions et réponses a été créée. Ludivine se charge de la transformer en JSon. Reste à augmenter sa taille et à incorporer la banque des Q/R liée aux partenaires.
